import type { EvidenceReference, ProjectMetadata } from "@/content/projects/types";

const reviewedOn = "2026-10-02";

function reviewedEvidence(slug: string): EvidenceReference[] {
  return [
    {
      id: `${slug}-scope`,
      label: "High-level capabilities reviewed against project documentation",
      kind: "documentation-reviewed",
      confirmedOn: reviewedOn,
    },
    {
      id: `${slug}-contribution`,
      label: "Contributor role corroborated by local commit-author attribution",
      kind: "repository-authorship",
      confirmedOn: reviewedOn,
    },
  ];
}

// Curated descriptions only. No private repository URLs, source excerpts,
// infrastructure identifiers, datasets, or unpublished evaluation claims.
// Card readiness is independent of the stricter case-study publication gate.
export const privateProjects = [
  {
    slug: "smart-vault",
    catalogOrder: 3,
    title: "Smart Vault",
    kicker: "Personal finance workspace",
    summary:
      "A personal finance application that brings accounts, transactions, budgets, and planning into one workspace.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "needs-confirmation",
    source: { kind: "private" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: reviewedEvidence("smart-vault"),
    showcase: {
      publication: "publishable",
      problem: "Financial activity and upcoming obligations can be difficult to review across separate accounts and tools.",
      contribution: "Contributed to the application’s interface and backend for reviewing finances and planning ahead.",
      role: { label: "Software contributor", evidenceIds: ["smart-vault-contribution"] },
      potentialValue: "Could make it easier to understand cash needs and financial priorities in one place.",
      evidenceIds: ["smart-vault-scope"],
      reviewedOn,
    },
  },
  {
    slug: "life-orchestrator",
    catalogOrder: 4,
    title: "Life Orchestrator",
    kicker: "Personal AI coordination",
    summary:
      "A personal AI coordination system that manages assistant requests, permissions, and human approvals.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "needs-confirmation",
    source: { kind: "private" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: reviewedEvidence("life-orchestrator"),
    showcase: {
      publication: "publishable",
      problem: "Personal AI tools need a consistent way to coordinate work while keeping sensitive actions under human control.",
      contribution: "Contributed to the orchestration backend and operator dashboard, including documented approval workflows.",
      role: { label: "Software contributor", evidenceIds: ["life-orchestrator-contribution"] },
      potentialValue: "Could help people supervise assistant activity and keep permission decisions consistent across tools.",
      evidenceIds: ["life-orchestrator-scope"],
      reviewedOn,
    },
  },
  {
    slug: "kinscape",
    catalogOrder: 5,
    title: "Kinscape",
    kicker: "Market research and personal watchlists",
    summary: "A market-research workspace with quotes, news, and personal watchlists for signed-in users.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "needs-confirmation",
    source: { kind: "private" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: [
      ...reviewedEvidence("kinscape"),
      {
        id: "kinscape-identity",
        label: "Unified research and account-based watchlist scope confirmed by the project owner",
        kind: "owner-confirmed",
        confirmedOn: reviewedOn,
      },
    ],
    showcase: {
      publication: "publishable",
      problem: "Researching a company can mean moving between quote pages, news, and separate lists of companies to follow.",
      contribution: "Contributed to the market-research application and its interface for reviewing research and personal watchlists.",
      role: { label: "Software contributor", evidenceIds: ["kinscape-contribution"] },
      potentialValue: "Could help users organize market research around the companies they follow, with watchlists tied to their account.",
      evidenceIds: ["kinscape-scope", "kinscape-identity"],
      reviewedOn,
    },
  },
  {
    slug: "home-llm",
    catalogOrder: 6,
    title: "Home LLM",
    kicker: "Personal AI chat interface",
    summary:
      "A private chat interface for a personal AI system, with conversation history, model choices, and approval prompts.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "needs-confirmation",
    source: { kind: "private" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: reviewedEvidence("home-llm"),
    showcase: {
      publication: "publishable",
      problem: "Working with a personal AI system needs a usable interface for conversations and supervised actions.",
      contribution: "Contributed to the chat application, including its documented conversation-management interface.",
      role: { label: "Software contributor", evidenceIds: ["home-llm-contribution"] },
      potentialValue: "Could make a personal AI system easier to use while keeping approval decisions visible.",
      evidenceIds: ["home-llm-scope"],
      reviewedOn,
    },
  },
  {
    slug: "prediction-arb-bot",
    catalogOrder: 7,
    title: "Prediction Arb Bot",
    kicker: "Inactive research project",
    summary:
      "An inactive research bot for comparing related prediction markets across exchanges.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "inactive",
    source: { kind: "private" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: [
      ...reviewedEvidence("prediction-arb-bot"),
      {
        id: "prediction-arb-bot-inactive",
        label: "Inactive status supplied by the project owner",
        kind: "owner-confirmed",
        confirmedOn: reviewedOn,
      },
    ],
    showcase: {
      publication: "publishable",
      problem: "Related prediction markets can be difficult to compare when exchanges describe and price events differently.",
      contribution: "Contributed to the research bot and API for reviewing market comparisons.",
      role: { label: "Software contributor", evidenceIds: ["prediction-arb-bot-contribution"] },
      potentialValue: "Could support discussion of market-data comparison and research limitations. No live trading access or returns are presented.",
      evidenceIds: ["prediction-arb-bot-scope", "prediction-arb-bot-inactive"],
      reviewedOn,
    },
  },
  {
    slug: "liquidity-optimizer",
    catalogOrder: 8,
    title: "Liquidity Optimizer",
    kicker: "Project scope awaiting confirmation",
    summary: "A potential showcase entry whose scope and relationship to Smart Vault need confirmation.",
    tags: [],
    featured: false,
    visual: "overview",
    publication: "unpublished",
    lifecycle: "needs-confirmation",
    source: { kind: "unconfirmed" },
    screenshots: [],
    video: { state: "unavailable" },
    evidence: [],
    showcase: {
      publication: "unpublished",
      pendingQuestions: [
        "Is this a standalone project or Smart Vault’s liquidity-planning feature?",
      ],
    },
  },
] satisfies ProjectMetadata[];
